### ISSUE TITLE
Add support for Rider 2023.1 EAP4

### ISSUE THREAD

**Issue by JanTamis** [carlrobertoh/ChatGPT#1]
Can you please add support for Rider 2023.1 EAP4?

**Comment by carlrobertoh** [comment]
Hey, thank you for filing an issue.
The support for 2023.* builds has been added and released.
https://github.com/carlrobertoh/ChatGPT/commit/172c73193e58e2e74a567f609f6d0c861e362659

**Comment by JanTamis** [comment]
Thanks!
