### ISSUE TITLE
Impossible to copy text from tool's window 

### ISSUE THREAD

**Issue by yonihorn** [carlrobertoh/ChatGPT#6]
Hi 😃 

I'm having two problems with the plugin:
1. markdown seems to not render 
2. the output is not copyable. it's impossible to select the text and right click on the panel doesn't seem to do anything.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/7020718/221381165-d1e27376-4653-44fc-9e10-89f21a806984.png">

Im using PyCharm 2023.1 EAP (Build #PY-231.7515.12)
Would appreciate any help!

**Comment by carlrobertoh** [comment]
Hi @yonihorn 

- The markdown is actually rendered but the library that I'm using doesn't support different language highlighting. Visual improvements are in my bucket list.
- The copy and selection functionality will be fixed in the next release (1.1.0)

Thank you!
