### ISSUE TITLE
Add Option To Select Other Language Models

### ISSUE THREAD

**Issue by mustafacakirogluK24** [carlrobertoh/ChatGPT#7]
Currently the requests we make use the Davinci base model, which is the most expensive model. For some quick and dirty questions the cheapest yet fastest model Ada or maybe the other 2 models which are between these two would've been more cost effective. Can we add an option to change base models?

[https://openai.com/api/pricing/](https://openai.com/api/pricing/)
<img width="1617" alt="Screenshot 2023-02-27 at 16 37 17" src="https://user-images.githubusercontent.com/101709759/221577968-4ed6c991-2687-41e9-b802-bc25425af1a8.png">

**Comment by carlrobertoh** [comment]
Hi @mustafacakirogluK24 

Good observation, I will add the option some time during this week.

FYI: I added a reverse proxy support for the real ChatGPT which should be free, in case you didn't get your account fixed. The release(1.1.0) is still pending by the JetBrains community tho.

Thank you!

**Comment by mustafacakirogluK24** [comment]
Thanks, I couldn't get my account fixed but I just made it a paid account, a few dollars a month shouldn't be an issue. I already updated the plugin to 1.1.1 from the github as soon as you released it, I am too impatient :)

**Comment by carlrobertoh** [comment]
The new version still has some bugs which I need to fix once I find some more time.
In the meantime, I'd really appreciate for a short review on JetBrains Marketplace if you're happy with the plugin.
Thank you!

**Comment by carlrobertoh** [comment]
Feature has been added to version [1.1.2](https://github.com/carlrobertoh/ChatGPT/releases/tag/1.1.2).
<img width="652" alt="Screen Shot 2023-02-27 at 23 56 49" src="https://user-images.githubusercontent.com/15891408/221716782-dcdf4246-c5b7-44e1-a08b-778bd40523e9.png">

Not sure how useful it will be since the responses are not that accurate comparing to the davinci's model.
